<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CS8618;CS8625;CS8629;CS1998;CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.26" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="NBomber" Version="5.7.1" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\AuthenticationService\AuthenticationService.API\AuthenticationService.API.csproj">
      <Aliases>AuthApi</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\..\Services\QueryService\QueryService.API\QueryService.API.csproj" />
    <ProjectReference Include="..\..\Services\ResidentialAreas\ResidentialAreas.API\ResidentialAreas.API.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.Messeging\BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
    <Using Include="Moq" />
  </ItemGroup>

</Project>
