services:
  residentialareas.api:
    image: ${DOCKER_REGISTRY-}residentialareasapi
    build:
      context: .
      dockerfile: Services/ResidentialAreas/ResidentialAreas.API/Dockerfile

  residentialareadb:      
    image: postgres:16 

    
  authenticationservicedb:
    image: mysql:8.0


  pgAdmin:
    image: dpage/pgadmin4:latest


  authenticationservice.api:
    image: ${DOCKER_REGISTRY-}authenticationserviceapi
    build:
      context: .
      dockerfile: Services/AuthenticationService/AuthenticationService.API/Dockerfile


  rabbitmq:
    image: rabbitmq:4-management

  kafka:
    image: confluentinc/cp-kafka:7.5.0

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0

  mongodb:
    image: mongo:7.0
    

  queryservice.api:
    image: ${DOCKER_REGISTRY-}queryserviceapi
    build:
      context: .
      dockerfile: Services/QueryService/QueryService.API/Dockerfile

volumes:
  residentialareadbdata:
  authenticationservicedbdata:
  rabbitmq_data:
  mongo_data:  
