services:
  residentialareas.api:
    image: ${DOCKER_REGISTRY-}residentialareasapi
    build:
      context: .
      dockerfile: Services/ResidentialAreas/ResidentialAreas.API/Dockerfile

  residentialareadb:      
    image: postgres:16 

  pgAdmin:
    image: dpage/pgadmin4:latest


volumes:
  residentialareadbdata: