services:
  residentialareas.api:
    build:
      context: .
      dockerfile: Services/ResidentialAreas/ResidentialAreas.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticPassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ../certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.crt:ro
    command: >
      sh -c "update-ca-certificates &&
             dotnet ResidentialAreas.API.dll"

  residentialareadb:
    container_name: residentialareadb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ResidentialAreasDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - residentialareadbdata:/var/lib/postgresql/data


  authenticationservicedb:
    container_name: authenticationdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_strong_Password123!
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticPassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
    ports:
      - "14330:1433"
    volumes:
      - authenticationservicedbdata:/var/opt/mssql


  pgAdmin:
    container_name: pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - residentialareadb


  authenticationservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticPassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - RabbitMQ__Host=amqp://guest:guest@rabbitmq:5672
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__EmailQueue=email_queue
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ../certs/authservice.pfx:/home/app/.aspnet/https/aspnetapp.pfx:ro
    depends_on:
      - authenticationservicedb
      - rabbitmq


  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
